apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
  namespace: tekton-tasks
spec:
  params:
  - name: repo-url
    type: string
  - name: webapp-reference-image
    type: string
    default: "michelechirico/polemicasite"
  - name: web-dockerfile-path
    type: string
    default: "./Dockerfile"
  - name: git-branch
    type: string
    default: "main"
  workspaces:
  - name: shared-data
    description: Cloned repo files shared across tasks
  - name: docker-credentials
    description: Docker credentials for pushing the image
  - name: ssh-credentials
    description: SSH credentials for git operations
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    - name: ssh-directory
      workspace: ssh-credentials
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.git-branch)
  - name: compute-version
    runAfter: [ "fetch-source" ]
    taskRef:
      name: compute-semver
    workspaces:
    - name: source
      workspace: shared-data
  - name: build-push-web
    runAfter: [ "compute-version" ]
    taskRef:
      name: buildah
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: docker-credentials
    params:
    - name: IMAGE
      value: $(params.webapp-reference-image):$(tasks.compute-version.results.new-version)
    - name: DOCKERFILE
      value: $(params.web-dockerfile-path)
    - name: CONTEXT
      value: .
  - name: update-deployment
    runAfter: [ "build-push-web" ]
    taskRef:
      name: update-deployment
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: image-tag
      value: $(tasks.compute-version.results.new-version)
    - name: deployment-path
      value: "eng/k8s/deployment-webapp.yaml"
  - name: git-tag-and-push
    runAfter: [ "update-deployment" ]
    taskRef:
      name: git-tag-and-push
    workspaces:
    - name: source
      workspace: shared-data
    - name: ssh-credentials
      workspace: ssh-credentials
    params:
    - name: release-version
      value: $(tasks.compute-version.results.new-version)
    - name: git-branch
      value: $(params.git-branch)
