apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polemicasite-jenkins-jcasc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/chiricomichele/polemicasite.git
    targetRevision: eng/move-to-jenkins
    path: k8s/jcasc
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
