apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jcasc-release
  namespace: jenkins
  labels:
    jenkins-jenkins-config: "true"
data:
  git-host-key-verification.yaml: |
    security:
      gitHostKeyVerificationConfiguration:
        sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
  credentials.yaml: |
    credentials:
      system:
        domainCredentials:
          - credentials:
              - basicSSHUserPrivateKey:
                  scope: GLOBAL
                  id: git-credentials
                  username: git
                  description: GitHub SSH key from Kubernetes secret
                  privateKeySource:
                    directEntry:
                      privateKey: "${id_ed25519}"
              - string:
                  scope: GLOBAL
                  id: docker-config-json
                  description: Docker config.json payload from Kubernetes secret
                  secret: "${DOCKER_CONFIG_JSON}"
  release-job.yaml: |
    jobs:
      - script: >
          pipelineJob('release') {
            description('Managed by GitOps and Jenkins Configuration as Code.')
            definition {
              cpsScm {
                lightweight(false)
                scm {
                  git {
                    remote {
                      url('ssh://git@ssh.github.com:443/chiricomichele/polemicasite.git')
                      credentials('git-credentials')
                    }
                    branch('*/eng/move-to-jenkins')
                  }
                }
                scriptPath('k8s/jcasc/Jenkinsfile.release')
              }
            }
            properties {
              disableConcurrentBuilds()
            }
            parameters {
              stringParam('GIT_BRANCH', 'main', 'Branch to build and update')
              stringParam('IMAGE_BASE', 'michelechirico/polemicasite', 'Docker image repository')
              stringParam('DOCKERFILE_PATH', './Dockerfile', 'Path to Dockerfile')
              stringParam('DEPLOYMENT_PATH', 'k8s/apps/deployment-webapp.yaml', 'Path to deployment manifest')
            }
          }
